# Generated by Django 5.2.5 on 2025-08-23 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ts_choicelog_made_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicelog',
            name='choice',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='choicelog',
            name='scene',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='choicelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
