# Generated by Django 5.2.5 on 2025-08-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_choicelog_choice_alter_choicelog_scene_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('is_start', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='emoji',
            field=models.CharField(default='✨', max_length=8),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(blank=True, max_length=32)),
                ('if_flags', models.JSONField(blank=True, default=dict)),
                ('set_flags', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('next_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.scene')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.scene')),
            ],
            options={
                'ordering': ('order', 'code'),
                'unique_together': {('scene', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ChoiceGain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains', to='core.choice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'unique_together': {('choice', 'item')},
            },
        ),
    ]
