# Generated by Django 5.2.5 on 2025-09-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prompt', models.TextField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('image_webp', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
