# Generated by Django 5.2.6 on 2025-09-30 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sceneart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('visit', 'Visit'), ('api', 'API Call')], default='visit', max_length=8)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'kind', 'provider'], name='core_traffi_created_1136df_idx')],
            },
        ),
    ]
