# Generated by Django 5.2.5 on 2025-09-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('text', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('url', models.URLField(blank=True, default='', max_length=800)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='copilot.doc')),
            ],
            options={
                'indexes': [models.Index(fields=['doc', 'order'], name='copilot_par_doc_id_6b1dfc_idx')],
            },
        ),
    ]
