# Generated by Django 5.2.6 on 2025-09-30 10:03

import copilot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_paragraph'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='openai', max_length=64)),
                ('model', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('http_status', models.IntegerField(default=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=copilot.models._now)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='copilot.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
