# Generated by Django 5.2.5 on 2025-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('short_desc', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech_tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
