name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: Bambicim.settings
      SECRET_KEY: dummy-secret-key
      PYTHONUNBUFFERED: "1"
      # If your settings gate storage by env, keep this ON to match prod:
      USE_MANIFEST_STATIC: "1"

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            poetry.lock

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Django system checks
        run: python manage.py check --deploy --fail-level WARNING

      # --- key part: build the static manifest before tests ---
      - name: Prepare STATIC_ROOT
        run: mkdir -p staticfiles
      - name: Collect static files
        run: python manage.py collectstatic --noinput
      # --------------------------------------------------------

      - name: Migrate (SQLite)
        run: python manage.py migrate --noinput

      - name: Run tests
        run: pytest -q
