name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: Bambicim.settings
      DJANGO_DEBUG: "False"
      DJANGO_SECRET_KEY: "dummy-ci-secret-key"
      ALLOWED_HOSTS: "localhost,127.0.0.1,testserver"
      CONTACT_RECIPIENT: "ci@example.com"
      # Optional GitHub API envs used by your homepage fetcher:
      GITHUB_USERNAME: "mertbayrakuni"
      GITHUB_TOKEN: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django ruff

      - name: Static analysis (ruff)
        run: |
          ruff --version
          ruff check .

      - name: Byte-compile sanity
        run: python -m compileall .

      - name: Django system checks
        run: python manage.py check --deploy --fail-level WARNING

      - name: Run tests
        run: pytest -q

      - name: Collect static (build sanity)
        run: python manage.py collectstatic --noinput
